import { constants as os } from "./os.mjs";

const names = [
  "COPYFILE_EXCL", "COPYFILE_FICLONE", "COPYFILE_FICLONE_FORCE", "DH_CHECK_P_NOT_PRIME", "DH_CHECK_P_NOT_SAFE_PRIME",
  "DH_NOT_SUITABLE_GENERATOR", "DH_UNABLE_TO_CHECK_GENERATOR", "E2BIG", "EACCES", "EADDRINUSE", "EADDRNOTAVAIL",
  "EAFNOSUPPORT", "EAGAIN", "EALREADY", "EBADF", "EBADMSG", "EBUSY", "ECANCELED", "ECHILD", "ECONNABORTED",
  "ECONNREFUSED", "ECONNRESET", "EDEADLK", "EDESTADDRREQ", "EDOM", "EDQUOT", "EEXIST", "EFAULT", "EFBIG",
  "EHOSTUNREACH", "EIDRM", "EILSEQ", "EINPROGRESS", "EINTR", "EINVAL", "EIO", "EISCONN", "EISDIR", "ELOOP",
  "EMFILE", "EMLINK", "EMSGSIZE", "EMULTIHOP", "ENAMETOOLONG", "ENETDOWN", "ENETRESET", "ENETUNREACH", "ENFILE",
  "ENGINE_METHOD_ALL", "ENGINE_METHOD_CIPHERS", "ENGINE_METHOD_DH", "ENGINE_METHOD_DIGESTS", "ENGINE_METHOD_DSA",
  "ENGINE_METHOD_EC", "ENGINE_METHOD_NONE", "ENGINE_METHOD_PKEY_ASN1_METHS", "ENGINE_METHOD_PKEY_METHS", "ENGINE_METHOD_RAND",
  "ENGINE_METHOD_RSA", "ENOBUFS", "ENODATA", "ENODEV", "ENOENT", "ENOEXEC", "ENOLCK", "ENOLINK", "ENOMEM", "ENOMSG",
  "ENOPROTOOPT", "ENOSPC", "ENOSR", "ENOSTR", "ENOSYS", "ENOTCONN", "ENOTDIR", "ENOTEMPTY", "ENOTSOCK", "ENOTSUP",
  "ENOTTY", "ENXIO", "EOPNOTSUPP", "EOVERFLOW", "EPERM", "EPIPE", "EPROTO", "EPROTONOSUPPORT", "EPROTOTYPE", "ERANGE",
  "EROFS", "ESPIPE", "ESRCH", "ESTALE", "ETIME", "ETIMEDOUT", "ETXTBSY", "EWOULDBLOCK", "EXDEV",
  "EXTENSIONLESS_FORMAT_JAVASCRIPT", "EXTENSIONLESS_FORMAT_WASM", "F_OK", "OPENSSL_VERSION_NUMBER", "O_APPEND", "O_CREAT",
  "O_DIRECT", "O_DIRECTORY", "O_DSYNC", "O_EXCL", "O_NOATIME", "O_NOCTTY", "O_NOFOLLOW", "O_NONBLOCK", "O_RDONLY",
  "O_RDWR", "O_SYMLINK", "O_SYNC", "O_TRUNC", "O_WRONLY", "POINT_CONVERSION_COMPRESSED", "POINT_CONVERSION_HYBRID",
  "POINT_CONVERSION_UNCOMPRESSED", "PRIORITY_ABOVE_NORMAL", "PRIORITY_BELOW_NORMAL", "PRIORITY_HIGH", "PRIORITY_HIGHEST",
  "PRIORITY_LOW", "PRIORITY_NORMAL", "RSA_NO_PADDING", "RSA_PKCS1_OAEP_PADDING", "RSA_PKCS1_PADDING", "RSA_PKCS1_PSS_PADDING",
  "RSA_PSS_SALTLEN_AUTO", "RSA_PSS_SALTLEN_DIGEST", "RSA_PSS_SALTLEN_MAX_SIGN", "RSA_X931_PADDING", "RTLD_DEEPBIND",
  "RTLD_GLOBAL", "RTLD_LAZY", "RTLD_LOCAL", "RTLD_NOW", "R_OK", "SIGABRT", "SIGALRM", "SIGBUS", "SIGCHLD", "SIGCONT",
  "SIGFPE", "SIGHUP", "SIGILL", "SIGINFO", "SIGINT", "SIGIO", "SIGIOT", "SIGKILL", "SIGPIPE", "SIGPOLL", "SIGPROF",
  "SIGPWR", "SIGQUIT", "SIGSEGV", "SIGSTKFLT", "SIGSTOP", "SIGSYS", "SIGTERM", "SIGTRAP", "SIGTSTP", "SIGTTIN",
  "SIGTTOU", "SIGURG", "SIGUSR1", "SIGUSR2", "SIGVTALRM", "SIGWINCH", "SIGXCPU", "SIGXFSZ", "SSL_OP_ALL",
  "SSL_OP_ALLOW_NO_DHE_KEX", "SSL_OP_ALLOW_UNSAFE_LEGACY_RENEGOTIATION", "SSL_OP_CIPHER_SERVER_PREFERENCE", "SSL_OP_CISCO_ANYCONNECT",
  "SSL_OP_COOKIE_EXCHANGE", "SSL_OP_CRYPTOPRO_TLSEXT_BUG", "SSL_OP_DONT_INSERT_EMPTY_FRAGMENTS", "SSL_OP_LEGACY_SERVER_CONNECT",
  "SSL_OP_NO_COMPRESSION", "SSL_OP_NO_ENCRYPT_THEN_MAC", "SSL_OP_NO_QUERY_MTU", "SSL_OP_NO_RENEGOTIATION",
  "SSL_OP_NO_SESSION_RESUMPTION_ON_RENEGOTIATION", "SSL_OP_NO_SSLv2", "SSL_OP_NO_SSLv3", "SSL_OP_NO_TICKET", "SSL_OP_NO_TLSv1",
  "SSL_OP_NO_TLSv1_1", "SSL_OP_NO_TLSv1_2", "SSL_OP_NO_TLSv1_3", "SSL_OP_PRIORITIZE_CHACHA", "SSL_OP_TLS_ROLLBACK_BUG",
  "S_IFBLK", "S_IFCHR", "S_IFDIR", "S_IFIFO", "S_IFLNK", "S_IFMT", "S_IFREG", "S_IFSOCK", "S_IRGRP", "S_IROTH",
  "S_IRUSR", "S_IRWXG", "S_IRWXO", "S_IRWXU", "S_IWGRP", "S_IWOTH", "S_IWUSR", "S_IXGRP", "S_IXOTH", "S_IXUSR",
  "TLS1_1_VERSION", "TLS1_2_VERSION", "TLS1_3_VERSION", "TLS1_VERSION", "UV_DIRENT_BLOCK", "UV_DIRENT_CHAR", "UV_DIRENT_DIR",
  "UV_DIRENT_FIFO", "UV_DIRENT_FILE", "UV_DIRENT_LINK", "UV_DIRENT_SOCKET", "UV_DIRENT_UNKNOWN", "UV_FS_COPYFILE_EXCL",
  "UV_FS_COPYFILE_FICLONE", "UV_FS_COPYFILE_FICLONE_FORCE", "UV_FS_O_FILEMAP", "UV_FS_SYMLINK_DIR", "UV_FS_SYMLINK_JUNCTION",
  "W_OK", "X_OK", "defaultCipherList", "defaultCoreCipherList",
];

const values = Object.fromEntries(names.map(name => [name, 0]));
Object.assign(values, os.errno, os.signals, os.dlopen, os.priority, {
  COPYFILE_EXCL: 1, COPYFILE_FICLONE: 2, COPYFILE_FICLONE_FORCE: 4,
  EXTENSIONLESS_FORMAT_JAVASCRIPT: 0, EXTENSIONLESS_FORMAT_WASM: 1, F_OK: 0,
  O_RDONLY: 0, O_WRONLY: 1, O_RDWR: 2, O_CREAT: 64, O_EXCL: 128, O_TRUNC: 512, O_APPEND: 1024, O_DIRECTORY: 65536,
  O_NOATIME: 262144, O_NOCTTY: 256, O_NOFOLLOW: 131072, O_NONBLOCK: 2048, O_SYNC: 1052672, O_DSYNC: 4096, O_DIRECT: 16384,
  R_OK: 4, W_OK: 2, X_OK: 1, SIGINFO: 29, SIGSTKFLT: 16,
  S_IFMT: 61440, S_IFREG: 32768, S_IFDIR: 16384, S_IFCHR: 8192, S_IFBLK: 24576, S_IFIFO: 4096, S_IFLNK: 40960, S_IFSOCK: 49152,
  S_IRWXU: 448, S_IRUSR: 256, S_IWUSR: 128, S_IXUSR: 64, S_IRWXG: 56, S_IRGRP: 32, S_IWGRP: 16, S_IXGRP: 8,
  S_IRWXO: 7, S_IROTH: 4, S_IWOTH: 2, S_IXOTH: 1,
  UV_DIRENT_UNKNOWN: 0, UV_DIRENT_FILE: 1, UV_DIRENT_DIR: 2, UV_DIRENT_LINK: 3, UV_DIRENT_FIFO: 4, UV_DIRENT_SOCKET: 5,
  UV_DIRENT_CHAR: 6, UV_DIRENT_BLOCK: 7, UV_FS_SYMLINK_DIR: 1, UV_FS_SYMLINK_JUNCTION: 2, UV_FS_COPYFILE_EXCL: 1,
  UV_FS_COPYFILE_FICLONE: 2, UV_FS_COPYFILE_FICLONE_FORCE: 4, UV_FS_O_FILEMAP: 0,
  defaultCipherList: "", defaultCoreCipherList: "",
});

export const constants = values;
export default constants;
