[package]
name = "tokamak-cli"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[[bin]]
name = "tok"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
tokamak = { path = "../tokamak" }
clap.workspace = true
ctrlc.workspace = true
getrandom.workspace = true
hex.workspace = true
mime_guess.workspace = true
netdev.workspace = true
rustls.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-rustls.workspace = true
tokio-util.workspace = true
walkdir.workspace = true

[target.'cfg(windows)'.dependencies]
win32job.workspace = true

[dev-dependencies]
assert_cmd.workspace = true
predicates.workspace = true
rcgen.workspace = true
tempfile.workspace = true

[lints]
workspace = true
