[package]
name = "tokamak-cli"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[[bin]]
name = "tok"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
tokamak = { path = "../tokamak" }
tokamak-apple-signing = { path = "../platforms/apple/signing" }
clap.workspace = true
getrandom.workspace = true
netdev.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["macros", "signal", "sync"] }
walkdir.workspace = true

[dev-dependencies]
assert_cmd.workspace = true
predicates.workspace = true
tempfile.workspace = true

[lints]
workspace = true
