#!/usr/bin/env node
import { execFileSync } from "node:child_process";
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { tmpdir } from "node:os";
import path from "node:path";

const revision = "v1.20260825.1";
const repository = `https://raw.githubusercontent.com/cloudflare/workerd/${revision}`;
const temporary = mkdtempSync(path.join(tmpdir(), "tokamak-d1-api-"));
const output = new URL("../tokamak/src/storage/", import.meta.url);

// The workerd-internal modules d1-api.ts imports, provided beside it.
const shims = {
  "cloudflare-internal:tracing-helpers": "./tracing-helpers.mjs",
  "cloudflare-internal:wrapped-binding": "./wrapped-binding.mjs",
};

async function download(file) {
  const response = await fetch(`${repository}/${file}`);
  if (!response.ok) throw new Error(`Failed to download ${file}: ${response.status}`);
  return response.text();
}

try {
  execFileSync("npm", ["install", "--prefix", temporary, "--cache", path.join(temporary, "cache"),
    "--ignore-scripts", "--no-audit", "--no-fund", "esbuild@0.25.9"], { stdio: "inherit" });
  const require = createRequire(path.join(temporary, "package.json"));
  const { transform } = require("esbuild");
  const source = await download("src/cloudflare/internal/d1-api.ts");
  let { code } = await transform(source, { loader: "ts", format: "esm", target: "es2022" });
  for (const [internal, shim] of Object.entries(shims)) {
    if (!code.includes(`"${internal}"`)) throw new Error(`d1-api.ts no longer imports ${internal}`);
    code = code.replaceAll(`"${internal}"`, `"${shim}"`);
  }
  writeFileSync(new URL("d1-api.mjs", output),
    `// Generated by scripts/vendor-d1-api.mjs from workerd ${revision} src/cloudflare/internal/d1-api.ts.\n` +
    "// Copyright (c) 2023 Cloudflare, Inc. Licensed under the Apache License 2.0; see WORKERD-LICENSE.\n" +
    code);
  writeFileSync(new URL("WORKERD-LICENSE", output), await download("LICENSE"));
} finally {
  rmSync(temporary, { recursive: true, force: true });
}
