//! Runtime-owned JavaScript module registry.

/// Every JavaScript compatibility module compiled into the runtime image.
#[allow(dead_code)]
pub(crate) const BUILTIN_SOURCES: &[&str] = &[
    "builtins/runtime.mjs",
    "builtins/globals.mjs",
    "builtins/async-context.mjs",
    "builtins/cloudflare-workers.mjs",
    "builtins/cloudflare-sockets.mjs",
    "builtins/cloudflare-node.mjs",
    "builtins/tracing.mjs",
    "events/events.mjs",
    "events/web.mjs",
    "globals/console.mjs",
    "globals/process.mjs",
    "globals/structured-clone.mjs",
    "globals/objects.mjs",
    "globals/performance.mjs",
    "globals/web.mjs",
    "intl.mjs",
    "network/fetch.mjs",
    "network/html-rewriter.mjs",
    "network/url.mjs",
    "network/websocket.mjs",
    "node/assert.mjs",
    "node/assert-strict.mjs",
    "node/async-hooks.mjs",
    "node/buffer.mjs",
    "node/child-process.mjs",
    "node/cluster.mjs",
    "node/console.mjs",
    "node/constants.mjs",
    "node/crypto.mjs",
    "node/diagnostics-channel.mjs",
    "node/dgram.mjs",
    "node/dns.mjs",
    "node/dns-promises.mjs",
    "node/domain.mjs",
    "node/http.mjs",
    "node/http2.mjs",
    "node/inspector.mjs",
    "node/internal-http-agent.mjs",
    "node/internal-http-client.mjs",
    "node/internal-http-common.mjs",
    "node/internal-http-incoming.mjs",
    "node/internal-http.mjs",
    "node/internal-http-outgoing.mjs",
    "node/internal-http-server.mjs",
    "node/internal-stream-duplex.mjs",
    "node/internal-stream-passthrough.mjs",
    "node/internal-stream-readable.mjs",
    "node/internal-stream-transform.mjs",
    "node/internal-stream-wrap.mjs",
    "node/internal-stream-writable.mjs",
    "node/internal-tls-common.mjs",
    "node/internal-tls-wrap.mjs",
    "node/https.mjs",
    "node/module.mjs",
    "node/net.mjs",
    "node/os.mjs",
    "node/path.mjs",
    "node/path-posix.mjs",
    "node/path-win32.mjs",
    "node/perf-hooks.mjs",
    "node/punycode.mjs",
    "node/querystring.mjs",
    "node/readline.mjs",
    "node/readline-promises.mjs",
    "node/repl.mjs",
    "node/string-decoder.mjs",
    "node/stream-consumers.mjs",
    "node/stream-promises.mjs",
    "node/stream-web.mjs",
    "node/sqlite.mjs",
    "node/timers.mjs",
    "node/timers-promises.mjs",
    "node/tls.mjs",
    "node/tty.mjs",
    "node/trace-events.mjs",
    "node/url.mjs",
    "node/util.mjs",
    "node/util-types.mjs",
    "node/unsupported.mjs",
    "node/v8.mjs",
    "node/vm.mjs",
    "node/wasi.mjs",
    "node/worker-threads.mjs",
    "node/zlib.mjs",
    "node/test.mjs",
    "streams/node.mjs",
    "streams/text.mjs",
    "streams/web.mjs",
    "streams/web-standard.mjs",
];

#[allow(dead_code)]
const PUBLIC_MODULES: &[(&str, &str)] = &[
    (
        "cloudflare:workers",
        "tokamak:builtins/cloudflare-workers.mjs",
    ),
    (
        "cloudflare:sockets",
        "tokamak:builtins/cloudflare-sockets.mjs",
    ),
    ("cloudflare:node", "tokamak:builtins/cloudflare-node.mjs"),
    ("node:assert", "tokamak:node/assert.mjs"),
    ("node:assert/strict", "tokamak:node/assert-strict.mjs"),
    ("node:async_hooks", "tokamak:node/async-hooks.mjs"),
    ("node:buffer", "tokamak:node/buffer.mjs"),
    ("node:child_process", "tokamak:node/child-process.mjs"),
    ("node:cluster", "tokamak:node/cluster.mjs"),
    ("node:console", "tokamak:node/console.mjs"),
    ("node:constants", "tokamak:node/constants.mjs"),
    ("node:crypto", "tokamak:node/crypto.mjs"),
    (
        "node:diagnostics_channel",
        "tokamak:node/diagnostics-channel.mjs",
    ),
    ("node:dgram", "tokamak:node/dgram.mjs"),
    ("node:dns", "tokamak:node/dns.mjs"),
    ("node:dns/promises", "tokamak:node/dns-promises.mjs"),
    ("node:domain", "tokamak:node/domain.mjs"),
    ("node:events", "tokamak:events/events.mjs"),
    ("node:fs", "node:fs"),
    ("node:fs/promises", "node:fs/promises"),
    ("node:http", "tokamak:node/http.mjs"),
    ("node:http2", "tokamak:node/http2.mjs"),
    ("node:inspector", "tokamak:node/inspector.mjs"),
    ("node:inspector/promises", "tokamak:node/inspector.mjs"),
    ("node:_http_agent", "tokamak:node/internal-http-agent.mjs"),
    ("node:_http_client", "tokamak:node/internal-http-client.mjs"),
    ("node:_http_common", "tokamak:node/internal-http-common.mjs"),
    (
        "node:_http_incoming",
        "tokamak:node/internal-http-incoming.mjs",
    ),
    (
        "node:_http_outgoing",
        "tokamak:node/internal-http-outgoing.mjs",
    ),
    ("node:_http_server", "tokamak:node/internal-http-server.mjs"),
    ("node:https", "tokamak:node/https.mjs"),
    ("node:module", "tokamak:node/module.mjs"),
    ("node:net", "tokamak:node/net.mjs"),
    ("node:_tls_common", "tokamak:node/internal-tls-common.mjs"),
    ("node:_tls_wrap", "tokamak:node/internal-tls-wrap.mjs"),
    ("node:os", "tokamak:node/os.mjs"),
    ("node:path", "tokamak:node/path.mjs"),
    ("node:path/posix", "tokamak:node/path-posix.mjs"),
    ("node:path/win32", "tokamak:node/path-win32.mjs"),
    ("node:perf_hooks", "tokamak:node/perf-hooks.mjs"),
    ("node:process", "tokamak:globals/process.mjs"),
    ("node:punycode", "tokamak:node/punycode.mjs"),
    ("node:querystring", "tokamak:node/querystring.mjs"),
    ("node:stream", "tokamak:streams/node.mjs"),
    ("node:stream/consumers", "tokamak:node/stream-consumers.mjs"),
    ("node:stream/promises", "tokamak:node/stream-promises.mjs"),
    ("node:stream/web", "tokamak:node/stream-web.mjs"),
    ("node:string_decoder", "tokamak:node/string-decoder.mjs"),
    ("node:sys", "tokamak:node/util.mjs"),
    ("node:timers", "tokamak:node/timers.mjs"),
    ("node:timers/promises", "tokamak:node/timers-promises.mjs"),
    ("node:tls", "tokamak:node/tls.mjs"),
    ("node:tty", "tokamak:node/tty.mjs"),
    ("node:url", "tokamak:node/url.mjs"),
    ("node:util", "tokamak:node/util.mjs"),
    ("node:util/types", "tokamak:node/util-types.mjs"),
    ("node:zlib", "tokamak:node/zlib.mjs"),
    ("node:readline", "tokamak:node/readline.mjs"),
    (
        "node:readline/promises",
        "tokamak:node/readline-promises.mjs",
    ),
    ("node:repl", "tokamak:node/repl.mjs"),
    ("node:v8", "tokamak:node/v8.mjs"),
    ("node:vm", "tokamak:node/vm.mjs"),
    ("node:worker_threads", "tokamak:node/worker-threads.mjs"),
    (
        "node:_stream_duplex",
        "tokamak:node/internal-stream-duplex.mjs",
    ),
    (
        "node:_stream_passthrough",
        "tokamak:node/internal-stream-passthrough.mjs",
    ),
    (
        "node:_stream_readable",
        "tokamak:node/internal-stream-readable.mjs",
    ),
    (
        "node:_stream_transform",
        "tokamak:node/internal-stream-transform.mjs",
    ),
    ("node:_stream_wrap", "tokamak:node/internal-stream-wrap.mjs"),
    (
        "node:_stream_writable",
        "tokamak:node/internal-stream-writable.mjs",
    ),
    ("node:sqlite", "tokamak:node/sqlite.mjs"),
    ("node:test", "tokamak:node/test.mjs"),
    ("node:trace_events", "tokamak:node/trace-events.mjs"),
    ("node:wasi", "tokamak:node/wasi.mjs"),
];

/// Return every public import spelling handled by the runtime resolver.
#[allow(dead_code)]
#[must_use]
pub fn runtime_module_names() -> Vec<&'static str> {
    let mut names = Vec::with_capacity(PUBLIC_MODULES.len() * 2);
    names.extend(PUBLIC_MODULES.iter().map(|(name, _)| *name));
    names.extend(
        PUBLIC_MODULES
            .iter()
            .filter_map(|(name, _)| name.strip_prefix("node:")),
    );
    names
}

#[allow(dead_code)]
pub(crate) fn public_module(name: &str) -> Option<&'static str> {
    PUBLIC_MODULES.iter().find_map(|(public, target)| {
        (*public == name
            || (!name.starts_with("node:") && public.strip_prefix("node:") == Some(name)))
        .then_some(*target)
    })
}
